apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3002
  type: ClusterIP
# then run kubectl apply -f service1-service.yaml
