apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3003
  type: ClusterIP
# then run kubectl apply -f service2-service.yaml
